spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: rexlee33
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.cfg.ImprovedNamungStrategy
    properties:
     hibernate: 
      dialect= org.hibernate.dialect.MySQL5InnoDBDialect

      